### ISSUE TITLE
Allow data-draggable to be set in components

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-react-bootstrap#121]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi,

Was trying to get the desktop app, using webview2 and using modus react.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/1041352/191903363-50b4e0ba-c75a-4ee4-9bc1-35a6d4a6b6e3.png">

Looks like modus is somehow suppressing data-draggable so i cant capture drag events. For example this will be important if creating diagrams that we need to drag and drop. 

In my particular case is a window chrome that i want to simulate for a desktop app.  

### Motivation and context

Desktop app

**Comment by msankaran0712** [comment]
> ### Prerequisites
> * [x]  I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
> * [x]  I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)
> 
> ### Proposal
> Hi,
> 
> Was trying to get the desktop app, using webview2 and using modus react.
> 
> <img alt="image" width="783" src="https://user-images.githubusercontent.com/1041352/191903363-50b4e0ba-c75a-4ee4-9bc1-35a6d4a6b6e3.png">
> 
> Looks like modus is somehow suppressing data-draggable so i cant capture drag events. For example this will be important if creating diagrams that we need to drag and drop.
> 
> In my particular case is a window chrome that i want to simulate for a desktop app.
> 
> ### Motivation and context
> Desktop app

Thank you for reporting, we will look into the issue.

**Comment by jmecosta** [comment]
in fact i need to draglle in all elements on the app bar... after this it works.. 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/1041352/191945090-32a568e3-9b56-46fb-953d-ae206feb3103.png">

sorry for the noise
