### ISSUE TITLE
React DataTable Column Resizing Not Being Applied

### ISSUE THREAD

**Issue by owebb98** [trimble-oss/modus-react-bootstrap#183]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using DataTable, adding the `resizeColumns` prop makes no functional difference and the columns are still fixed size.

By setting a breakpoint in DataTable.js in Chrome DevTools, you can see that without the prop, `resizeColumns` is undefined:
![image](https://user-images.githubusercontent.com/59833224/196730715-dc0c7db0-65ac-43a9-8fe2-538452fb59de.png)
![image](https://user-images.githubusercontent.com/59833224/196730634-2faf94e3-0bf9-4a72-b7d9-83ae6f70dfeb.png)

And then when the prop is present, it is set to true:
![image](https://user-images.githubusercontent.com/59833224/196731643-f90acb3a-7edf-4481-b8db-ac1253a82c1e.png)
![image](https://user-images.githubusercontent.com/59833224/196731574-c4a47465-916b-4117-b824-613ccf4a5c97.png)

So the props are being set correctly but from there, the value isn't being applied correctly.

This issue persists even when explicitly setting `disableResizing` to false in the column defs.

npm 8.15.0
node 16.17.0

### Reduced test cases

        <DataTable
          id="activities_table"
          columns={ACTIVITIES_FIELDS} bordered hover
          responsive
          disablePagination
          data={MOCK_ACTIVITIES}
          resizeColumns
        ></DataTable>

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome 106

### What version of Modus React Bootstrap are you using?

v1.1.4

### Priority

Medium

**Comment by msankaran0712** [comment]
@owebb98 I talked to chelsea_williams@trimble.com and the issue seems to be fixed. Please confirm.

**Comment by owebb98** [comment]
> @owebb98 I talked to [chelsea_williams@trimble.com](mailto:chelsea_williams@trimble.com) and the issue seems to be fixed. Please confirm.

Hi @msankaran0712, yes, this is now working as expected after changing our styles.scss file to use '@trimbleinc/modus-react-bootstrap/css/dist/modus-react-bootstrap.min.css' instead of '@trimbleinc/modus-bootstrap/dist/modus.min.css'.

I will close this issue now. Many thanks
