### ISSUE TITLE
Messages - Dark theme colors are not correct, refer to Style guide

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-react-bootstrap#198]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The fix should be made in Modus Bootstrap and React will be updated following that.

Actual:
![image](https://user-images.githubusercontent.com/50131391/201273446-4320522c-9d95-44d9-a892-653e5c0628b6.png)

Expected:
![image](https://user-images.githubusercontent.com/50131391/201273521-2e6fd113-5839-4905-9e0a-07724d2bd3a3.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Modus React Bootstrap are you using?

1.x

### Priority

High

**Comment by coliff** [comment]
When this is approved and merged I'll look to ship a Modus Bootstrap release next week!
https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/284/overview

**Comment by coliff** [comment]
I think this issue can be closed now - issue resolved.
https://modus-react-bootstrap.trimble.com/components/messages/
