### ISSUE TITLE
File Upload Dropzone React Bootstrap Component

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/modus-react-bootstrap#26]
As a developer, I want to have the drag & drop component available in React Bootstrap, so I can use it for building my product.

**Comment by msankaran0712** [comment]
Preview
https://deploy-preview-172--modus-react-bootstrap.netlify.app/components/file-upload-dropzone/

**Comment by msankaran0712** [comment]
PR https://github.com/trimble-oss/website-modus-react-bootstrap.trimble.com/pull/172

**Comment by jeffdoolittle** [comment]
Is this something that can be implemented as a pure web component with bindings to react/angular/etc.?

**Comment by msankaran0712** [comment]
> Is this something that can be implemented as a pure web component with bindings to react/angular/etc.?

did you mean https://modus-web-components.trimble.com/?path=/docs/components-file-dropzone--default ?

**Comment by jeffdoolittle** [comment]
Precisely!

**Comment by msankaran0712** [comment]
> Precisely!

Did I answer your question? I was wondering whether I understood it right

**Comment by enowak1031** [comment]
- “Max files can be uploaded exceeds limit. Number of files uploaded is 4 and limit is 3.  Click here to reset.

Change to:
“Max file upload limit of 3 files exceeded. Click here to reset. “

- “Some of the files uploaded are not matching the allowed File types (“.pdf”, “image/jpeg”, “image/png”). Click here to reset.” 

Change to: 
“Some files do not match the allowed file types (“.pdf,” “image/jpeg,” “image/png”). Click here to reset.

**Comment by msankaran0712** [comment]
@enowak1031 ready for final review

**Comment by Balaji-trimble** [comment]
@enowak1031 @msankaran0712 Done with QA
