### ISSUE TITLE
Not able to sort in DataTable component when a component is defined inside the cell.

### ISSUE THREAD

**Issue by hgowtha** [trimble-oss/modus-react-bootstrap#268]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm passing an object as data for a particular column in DataTable.
( Sample: 
```ts
Data = [
  'Name' : {
    'id' : id,
    'name' : name
  }
]

Column = [
  {
    Header: "Name",
    accessor: "Name",
    sortBy: true,
    Cell: (row: any) => {
      return (
        <Link to={`/members/${row.value.id}`}>{row.value.name}</Link>
      )
    }
  }
]
```
But I'm not able to sort it by name.

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Modus React Bootstrap are you using?

1.1.4

### Priority

High

**Comment by msankaran0712** [comment]
As discussed with @hgowtha the accessor should actually read like `accessor: "Name.name"` because it is a nested object and there is one more option available and that is a property accepting a custom sort function and that will be available in the upcoming release of Modus react bootstrap.

**Comment by msankaran0712** [comment]
Closing the issue as the reported issue isn't really a bug and a PR is made to improve docs.

**Comment by msankaran0712** [comment]
@hgowtha Modus React Bootstrap's new version is available and please check out the [release notes](https://github.com/trimble-oss/modus-react-bootstrap/releases) before installing the latest.
