### ISSUE TITLE
Unable to close Toast component

### ISSUE THREAD

**Issue by VinoSakthi** [trimble-oss/modus-react-bootstrap#271]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Unable to close Toast Notification by clicking close button 
onClose method is not triggered when  close button clicked

![image](https://user-images.githubusercontent.com/29659426/220340104-e65c48ae-274f-496f-b34f-f060245b6da2.png)

### Reduced test cases

Create a Toast with onClose method using modus react bootstrap 
Click close button ,  onClose is not triggered

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Modus React Bootstrap are you using?

1.1.1

### Priority

High

**Comment by msankaran0712** [comment]
hi @VinoSakthi checking the issue we found that the `onClose` is supposed to be triggered when using the default close button inside `ToastHeader` tag so we are updating only the API description and doesn't require any other fix. If you are using a custom close button it is recommended to handle the onclose event on the button directly.
