### ISSUE TITLE
Outlined icon in Messages shows warning

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus-react-bootstrap#278]
Contact Us form input by  shun_kito@trimble.com

https://modus-react-bootstrap.trimble.com/components/messages/ 

Example code for   

```html
<Message
    icon="info"
    variant="primary"
    message="This is a primary message"
  ></Message>
```
gives a warning. The code expects a react element in the icon field, but the example suggests providing the string "info". If the way icons are specified is as described by https://modus-icons.trimble.com/modus-solid/info/ the correct code would be: 

```html
<Message
            icon={<i className="modus-icons" aria-hidden="true">info</i>}
            variant="primary"
            message="This is a primary message."
 ></Message>
```

**Comment by msankaran0712** [comment]
@soniakaukonen Please inform [shun_kito@trimble.com](mailto:shun_kito@trimble.com) that the issue is fixed and check out the [release notes](https://github.com/trimble-oss/modus-react-bootstrap/releases) before installing the latest version.
