### ISSUE TITLE
`lodash` is improperly specified as a devDependency

### ISSUE THREAD

**Issue by Kai-Richardson** [trimble-oss/modus-react-bootstrap#302]
### Prerequisites
- [x]  I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc) for duplicate or closed feature requests
- [x]  I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md?rgh-link-date=2023-03-17T11%3A54%3A24Z)

### Issue

Hi, when attempting to use this library, if you don't have [`lodash`](https://yarnpkg.com/package/lodash) specified as a dependency of your project, using some components and building it will fail in many cases:
```
> yarn install
Failed to compile.

Module not found: Error: Can't resolve 'lodash/merge' in 'C:\repo\.yarn\__virtual__\@trimbleinc-modus-react-bootstrap-virtual-1215b34c7b\0\cache\@trimbleinc-modus-react-bootstrap-npm-1.1.5-512b87a9a5-c1bc9712c1.zip\node_modules\@trimbleinc\modus-react-bootstrap\esm'
ERROR in ./.yarn/__virtual__/@trimbleinc-modus-react-bootstrap-virtual-1215b34c7b/0/cache/@trimbleinc-modus-react-bootstrap-npm-1.1.5-512b87a9a5-c1bc9712c1.zip/node_modules/@Module not found: Error: Can't resolve 'lodash/merge' in 'C:\repo\.yarn\__virtual__\@trimbleinc-modus-react-bootstrap-virtual-1215b34c7b\0\cache\@trimbleinc-modus-react-bootstrap-npm-1.1.5-512b87a9a5-c1bc9712c1.zip\node_modules\@trimbleinc\modus-react-bootstrap\esm'

ERROR in ./.yarn/__virtual__/@trimbleinc-modus-react-bootstrap-virtual-1215b34c7b/0/cache/@trimbleinc-modus-react-bootstrap-npm-1.1.5-512b87a9a5-c1bc9712c1.zip/node_modules/@trimbleinc/modus-react-bootstrap/esm/useTreeViewDescendants.js 19:0-49
Module not found: Error: Can't resolve 'lodash' in 'C:\repo\.yarn\__virtual__\@trimbleinc-modus-react-bootstrap-virtual-1215b34c7b\0\cache\@trimbleinc-modus-react-bootstrap-npm-1.1.5-512b87a9a5-c1bc9712c1.zip\node_modules\@trimbleinc\modus-react-bootstrap\esm'
```

This is due to the following line in the code:
https://github.com/trimble-oss/modus-react-bootstrap/blob/7b26323fc91aba9b55b9c9ff65454eb4bedc47bc/src/useTreeViewDescendants.tsx#L26-L30

It'd be great if this project could move lodash to be under `dependencies` in the `package.json`, as this would eliminate this unexpected error and be more correct, as far as dependency specification goes.

### Applicable Version

Current, `v1.1.5`

**Comment by msankaran0712** [comment]
Thanks for reporting the issue @Kai-Richardson, we are working on it.

**Comment by msankaran0712** [comment]
@Kai-Richardson The issue is fixed and kindly please check out the [release notes](https://github.com/trimble-oss/modus-react-bootstrap/releases) before installing the latest version.
