### ISSUE TITLE
Modus React Bootstrap - Update Blue NavBar colors  

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-react-bootstrap#316]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Look at the latest comment from Eric on https://github.com/trimble-oss/modus-web-components/issues/1058

### Motivation and context

NA

**Comment by coliff** [comment]
Think this issue can be closed? It'll be fixed with Modus Bootstrap 1.5.7 which should be available by Monday. Once it's published to npm this package can use it and issue will be resolved.

**Comment by msankaran0712** [comment]
@coliff Thank you 👍 I will make this issue in progress so that I can make a new release for React.

**Comment by coliff** [comment]
Feel free to make a new release now that Modus Bootstrap 1.6.0 update is merged!
