### ISSUE TITLE
pageSizeOptions set to one element, it should hide the pagination element

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-react-bootstrap#325]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi,

pageSizeOptions={[10]}

If we have only one option set to this option, it doesnt make much sense to show to user. Please consider hiding it so we have this

![image](https://user-images.githubusercontent.com/1041352/233725725-e0a902f4-bd4a-4aa5-8650-44c43f7511be.png)

thanks

### Motivation and context

usability

**Comment by msankaran0712** [comment]
Hi @jmecosta 

I regret to inform you that our main focus at this time is on Modus Web Components, and we will be placing Modus React Bootstrap into maintenance mode.
Our suggestion would be to transition to Web components. Additionally, if you are interested in contributing to Modus React Bootstrap, kindly submit a PR for our review.
