### ISSUE TITLE
Default behavior of the text in rows jumps to the next row

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-react-bootstrap#326]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,
checked the doc, i can crop the text, however i will loose ability to search the text in column. 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/1041352/233786965-4bb395e5-50ec-45b1-b90b-3bb64e163844.png">

If string is 2 long it will be on top of the other column.

thanks

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Modus React Bootstrap are you using?

1.2.0

### Priority

Medium

**Comment by msankaran0712** [comment]
Hi @jmecosta 

I regret to inform you that our main focus at this time is on Modus Web Components, and we will be placing Modus React Bootstrap into maintenance mode.
Our suggestion would be to transition to Web components. Additionally, if you are interested in contributing to Modus React Bootstrap, kindly submit a PR for our review.
