### ISSUE TITLE
Improve sorting icons in table

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-react-bootstrap#367]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi,

see
<img width="889" alt="image" src="https://github.com/trimble-oss/modus-react-bootstrap/assets/1041352/d23b509a-f6a3-4392-ba00-7108e45dafdd">

sorting buttons are a bit all over the place. Would be best if they would be alligned to text or hidden by default and show when hover like this
<img width="1406" alt="image" src="https://github.com/trimble-oss/modus-react-bootstrap/assets/1041352/97d1cdf6-ff3a-4665-9518-5c54c44ec023">
 and hover
<img width="1374" alt="image" src="https://github.com/trimble-oss/modus-react-bootstrap/assets/1041352/f7d3b3fa-58bc-4288-be2e-970346750b48">

### Motivation and context

usability

**Comment by msankaran0712** [comment]
@jmecosta 

At the moment, we are focusing on Modus Web Components as our top priority and putting Modus React Bootstrap in maintenance mode.
Our suggestion would be to transition to Web components. Additionally, if you are interested in contributing to Modus React Bootstrap, kindly submit a PR for our review.

**Comment by jmecosta** [comment]
@msankaran0712 could we update the documentation on https://modus-react-bootstrap.trimble.com/ to instruct people to use Modus Web Components, since we started not long with our project, it seems we have taken the incorrect approach since start. 

We will plan the migration shortly.

**Comment by msankaran0712** [comment]
Thank you for the feedback, @jmecosta and apologies for the inconvenience caused. We will update the Modus React Bootstrap site.
