### ISSUE TITLE
Compact Progress Bar in React Bootstrap

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-react-bootstrap#37]
As an engineer, I want to have the compact progress bar available in React Bootstrap, so I can use it in my application.

**Comment by msankaran0712** [comment]
@enowak1031  
preview
https://deploy-preview-166--modus-react-bootstrap.netlify.app/components/progress-bars/

**Comment by Balaji-trimble** [comment]
@msankaran0712 

In API table for _bsprefix_ description is missing but it is present in the https://react-bootstrap-v4.netlify.app/components/progress/

**Comment by msankaran0712** [comment]
> @msankaran0712
> 
> In API table for _bsprefix_ description is missing but it is present in the https://react-bootstrap-v4.netlify.app/components/progress/

Good observation. We should be good with it, for now, we will upgrade the React-bootstrap library really soon so this will be fixed automatically.

**Comment by Balaji-trimble** [comment]
@enowak1031 @msankaran0712 Verified this ticket. Hence moving it to PO review

**Comment by msankaran0712** [comment]
Closing the issue as it already done.
