### ISSUE TITLE
Debugger statements found in production packages

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-react-bootstrap#38]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

hi,

![image](https://user-images.githubusercontent.com/1041352/163114087-aafbf456-44ce-4d6a-b575-1566e49c8062.png)

these are found a bit all over the place... some places i can ignore, some i cant so debugging my own code is a bit difficult...

thanks

### Reduced test cases

not applicable

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Modus React Bootstrap are you using?

1.0.0

**Comment by msankaran0712** [comment]
@jmecosta Thanks for the feedback, fix will be available in the upcoming release.

**Comment by msankaran0712** [comment]
issue is fixed and will be available in @trimbleinc/modus-react-bootstrap@v1.1.0
