### ISSUE TITLE
OnDoubleClick feature to Datatable rows

### ISSUE THREAD

**Issue by Gnirps00** [trimble-oss/modus-react-bootstrap#391]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

OnDoubleClick feature to Datatable row, just like onRowSelectionChange={handleOnRowSelection}

### Motivation and context

Users might want to open a file or something from the table by double clicking on the row of it. This kind of feature can be seen also in Google Drive.

**Comment by msankaran0712** [comment]
Hey @Gnirps00 At the moment, we are focusing on Modus Web Components as our top priority and putting Modus React Bootstrap in maintenance mode. 
Our suggestion would be to transition to Web components. Additionally, if you are interested in contributing to Modus React Bootstrap, please don't hesitate to submit a PR for our review.
