### ISSUE TITLE
GitHub Action to run tests / linting on every PR

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-react-bootstrap#7]

**Comment by coliff** [comment]
It should run `npm run lint` to start with, but that currently gives 12 errors and 4 warnings (on main branch), so we should get those fixed before adding this.

**Comment by msankaran0712** [comment]
With new components added there are more eslint errors.

**Comment by coliff** [comment]
Maybe fix as many issues as you can and then add remaining eslint error/warnings to the eslint config in the ignore list and then tackle them one by one as you get a chance? I think that would be better than nothing.

**Comment by msankaran0712** [comment]
All the lint issues are fixed as part of the release v1.1.0 in [dev/release-v1.1.0](https://github.com/trimble-oss/modus-react-bootstrap/tree/dev/release-v1.1.0)  branch
