### ISSUE TITLE
Modus React Bootstrap - DataTable Component - Unnecessary space for checkbox column

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-react-bootstrap#76]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

![image](https://user-images.githubusercontent.com/50131391/175058859-bb6b6117-c4d2-4deb-9832-35b0749dbc28.png)

### Reduced test cases

None 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Modus React Bootstrap are you using?

1.1.0

### Priority

High

**Comment by msankaran0712** [comment]
Preview:
https://deploy-preview-219--modus-react-bootstrap.netlify.app/components/tables/#TablewithCheckBoxRowSelection

**Comment by Balaji-trimble** [comment]
@msankaran0712 @enowak1031 Verified this ticket in firefox, chrome and Edge browser.
